name: DynmapApi
version: "${project.version}"
main: de.codeinfection.quickwango.DynmapApi.DynmapApi
#commands:
depend:
  - ApiBukkit
  - dynmap
softdepend: []
database: false
website: "http://parallel-universe.de"
description: ""
author: "Quick_Wango"
authors:
  - "Quick_Wango"
load: postworld
