name: BasicApi
main: de.codeinfection.quickwango.BasicApi.BasicApi
version: "${project.version}"
description: "Exposes many parts of Bukkit as a Web API."
authors:
  - Quick_Wango
website: http://parallel-universe.de
depend:
  - ApiBukkit
