General:
    logLevel: DEFAULT
Network:
    port: 6561
    authKey: ''
    maxContentLength: 1048576
DisabledActions: {}
Blacklist:
    enabled: false
    IPs: []
Whitelist:
    enabled: false
    IPs: []
