name: ApiBukkit
main: de.codeinfection.quickwango.ApiBukkit.ApiBukkit
version: "${project.version}"
authors:
  - Phillip Schichtel
website: http://code-infection.de
commands:
  apibukkit:
    usage: /<command> [action]
    description: 'Actions are help, info and reload'
