name: ApiBukkit
main: de.codeinfection.quickwango.ApiBukkit.ApiBukkit
version: "${project.version}"
description: "Provides an API to mak Web APIs."
authors:
  - Quick_Wango
website: http://parallel-universe.de
commands:
  apibukkit:
    usage: /<command> [action]
    description: 'Actions are help, info and reload'
