name: ApiBukkit
main: de.codeinfection.quickwango.ApiBukkit.ApiBukkit
version: 0.3.2
authors:
  - Phillip Schichtel
website: http://code-infection.de
commands:
  apiinfo:
    usage: /<command>
    description: prints the API config to the sender
  apireload:
    usage: /<command>
    description: reloads the API server
